%YAML:1.0

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------
File.version: "1.0"

Camera.type: "PinHole"

# Right Camera calibration and distortion parameters (OpenCV)
Camera1.fx: 6.101335559441417e+02
Camera1.fy: 6.135861937618225e+02
Camera1.cx: 3.227614324987148e+02
Camera1.cy: 2.8397258711268006e+02
# distortion parameters
Camera1.k1: 1.27239143170079e-01
Camera1.k2: -1.7189525099448597e-01
Camera1.p1: 3.6598002109648545e-02
Camera1.p2: -5.475253359457955e-04

# Camera resolution
Camera.width: 640
Camera.height: 480

# Camera frames per second 
Camera.fps: 30

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1

Stereo.ThDepth: 150.0
Stereo.b: 0.0745

# Depth map values factor
RGBD.DepthMapFactor: 1000.0

# Transformation from body-frame (imu) to left camera
IMU.T_b_c1: !!opencv-matrix
   rows: 4
   cols: 4
   dt: f
   data: [0.9998459267770778, -0.014520237824831474, 0.009863336190023013, 0.016028076514402044,
         0.015038364877477233, 0.9983915800255388, -0.05466352088843629, -0.008291760635196736,
          -0.009053744479437414, 0.054803427152131504, 0.9984561152515832, -0.00628396240747243,
          0.0, 0.0, 0.0, 1.0]


# Do not insert KFs when recently lost
IMU.InsertKFsWhenLost: 0

# IMU noise (Use those from VINS-mono)
IMU.NoiseGyro: 2.049600985797649e-4 # 3 # 2.44e-4 #1e-3 # rad/s^0.5
IMU.NoiseAcc: 2.064189891192468e-3 #2 # 1.47e-3 #1e-2 # m/s^1.5
IMU.GyroWalk: 3.1998555455947417e-6 # rad/s^1.5
IMU.AccWalk: 2.2919238444020807e-4 # m/s^2.5
IMU.Frequency: 200.0

#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------
# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 2000

# ORB Extractor: Scale factor between levels in the scale pyramid 	
ORBextractor.scaleFactor: 1.2

# ORB Extractor: Number of levels in the scale pyramid	
ORBextractor.nLevels: 8

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast			
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 2

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1.0
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 2.0
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3.0
Viewer.ViewpointX: 0.0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -3.5
Viewer.ViewpointF: 500.0

